### PR TITLE
Update applicant-modal.json

### PR DESCRIPTION
**Pull request by PandorasFox**
the first of many

### CODE REVIEW

**Comment by PandorasFox** [comment]
I think that a couple bits 'n' pieces in guild-create-modal.json should be in the guild-join-policy.json

**Comment by PandorasFox** [comment]
I'm trying to weasel out another translation somewhere that needs fixed (I call cards "ships" now) so don't merge this yet please

[actually now I've got to finish the fractures tomorrow]

**Comment by PandorasFox** [comment]
I believe it's all done now. :smiley:

**Comment by PandorasFox** [comment]
i need to make a guide in the BTC on how to submit multiple things as one patch/pull

**Comment by jacob-grahn** [comment]
Thank you kindly. It suuure is easier to merge these if they're all together.

**Pull request merged**
